// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eskufzrcfwjfnlfllyhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVza3VmenJjZndqZm5sZmxseWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTYxOTQsImV4cCI6MjA2NjgzMjE5NH0.89ZmT2iXkwpH8kOzAlSmHvchziSCRvQZek6QNphz0yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});